import React from 'react';
import TestRenderer, { act } from 'react-test-renderer';
import { ProductTermsDisclosure } from '../src/components/product/ProductTermsDisclosure';
import { createTermsReferenceStore, previousTermsReference, type TermsReference } from '../src/data/termsReferenceStore';
import { canonicalTermsJson, TERMS_STAGES, validateProductTerms } from '../src/data/productTerms';
import { hashText } from '../src/lib/productTermsEngine/validation';
let mockState: any;
jest.mock('../src/data/store', () => ({ useStore: (selector: any) => selector(mockState) }));
jest.mock('../src/data/productTermsTransport', () => ({ loadProductTerms: jest.fn(async () => { throw new Error('offline'); }) }));
jest.mock('../src/data/termsReferenceStore', () => ({ ...jest.requireActual('../src/data/termsReferenceStore'), previousTermsReference: jest.fn() }));
jest.mock('../src/components/CustomerProfilePanel', () => ({ CustomerProfilePanel: 'CustomerProfilePanel' }));
jest.mock('../src/components/ExternalLinkConfirmation', () => ({ useTrustedExternalUrl: () => ({ requestExternalUrl: jest.fn() }) }));
jest.mock('../src/components/ui', () => ({ AppText: 'AppText', Button: 'Button', Disclosure: ({ children, open, ...props }: any) => jest.requireActual('react').createElement('Disclosure', { ...props, open }, open ? children : null) }));
test.each([true, false])('restart/offline retains descriptive evidence with correct matching-edition label (%s)', async same => {
  const body = { schema_version: 1, product_key: 'technical', documents: [], clauses: [], revisions: [], changes: [], coverage: { ...Object.fromEntries(TERMS_STAGES.map(stage => [stage, { status: 'unknown', expected: null, observed: 0 }])), gaps: ['Retained engineering reference'] } };
  const saved: TermsReference = { productKey: 'technical', edition: 'a'.repeat(64), runDate: '2026-09-15', indexSha256: 'b'.repeat(64), assetSha256: 'c'.repeat(64), retainedAt: '2026-09-15T00:00:00Z', terms: validateProductTerms({ ...body, identity_sha256: hashText(canonicalTermsJson(body)) }, 'technical') };
  const slots = new Map<number, string>(), storage = { read: async (slot: number) => slots.get(slot) ?? null, write: async (slot: number, text: string) => { slots.set(slot, text); } };
  await createTermsReferenceStore(storage).retain(saved);
  (previousTermsReference as jest.Mock).mockImplementation(createTermsReferenceStore(storage).previous);
  mockState = { manifest: { payload_revision: { bundle_sha256: (same ? 'a' : 'd').repeat(64) }, files: { terms_index: { sha256: 'b'.repeat(64) } } } };
  let tree: any;
  await act(async () => { tree = TestRenderer.create(<ProductTermsDisclosure productKey="technical" />); });
  await act(async () => tree.root.findByProps({ title: 'Document coverage and terms' }).props.onToggle());
  expect(JSON.stringify(tree.toJSON())).toContain('could not be verified');
  act(() => tree.root.findByProps({ title: 'Saved descriptive evidence' }).props.onToggle());
  expect(JSON.stringify(tree.toJSON())).toContain(same ? 'Saved evidence from this publication' : 'Earlier publication');
  expect(JSON.stringify(tree.toJSON())).toContain('not calculation approval');
  expect(JSON.stringify(tree.toJSON())).toContain('Retained engineering reference');
  act(() => tree.unmount());
});
