plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.eyex.australianrates'
version = '1.0.0'

android {
  namespace 'com.eyex.australianrates.apkidentity'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'com.android.tools.build:apksig:8.10.1'
}
